# Generated by Django 4.0.1 on 2022-01-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='repairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=45, verbose_name='ФИО')),
                ('contacts', models.IntegerField(verbose_name='Телефон')),
                ('brandCar', models.CharField(max_length=45, verbose_name='Марка автомобиля')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('problem', models.TextField(verbose_name='Проблема')),
                ('status', models.CharField(choices=[('1', 'Обработка'), ('2', 'В ремонте'), ('3', 'Выполнено')], default=1, max_length=3)),
            ],
        ),
    ]
